apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: bookstore
data:
  LOG_LEVEL: "info"
  ENVIRONMENT: "tp"
  MAX_CONNECTIONS: "50"
  FRONTEND_URL: "http://bookstore.local"
  API_PREFIX: "/api/v1"