apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
  namespace: bookstore
type: Opaque
stringData:
  POSTGRES_DB: bookstoredb
  POSTGRES_USER: bookuser
  POSTGRES_PASSWORD: Bookst0re@2026!
  DATABASE_URL: postgresql://bookuser:Bookst0re@2026!@postgres:5432/bookstoredb